version: '3.8'

# Development overrides for hot reloading and debugging
services:
  backend:
    build:
      context: ./app
      dockerfile: Dockerfile.dev
      target: development
    environment:
      - ENVIRONMENT=development
      - DEBUG=true
      - PYTHONPATH=/app
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    volumes:
      - ./app:/app
      - /app/__pycache__
      - /app/.pytest_cache
    command: uvicorn start:app --host 0.0.0.0 --port 8000 --reload --log-level debug
    stdin_open: true
    tty: true

  frontend:
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:8000
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - VITE_HMR_PORT=24678
    volumes:
      - .:/app
      - /app/node_modules
      - /app/dist
      - /app/.vite
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0 --port 8080 --force"
    stdin_open: true
    tty: true

  postgres:
    environment:
      - POSTGRES_LOG_STATEMENT=all
      - POSTGRES_LOG_MIN_DURATION_STATEMENT=0
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
      - ./scripts/dev-seed.sql:/docker-entrypoint-initdb.d/dev-seed.sql:ro
    ports:
      - "5432:5432"

  redis:
    command: redis-server --appendonly yes --maxmemory 128mb --maxmemory-policy allkeys-lru --loglevel debug
    volumes:
      - redis_data:/data
      - ./redis/redis-dev.conf:/usr/local/etc/redis/redis.conf:ro

  # Development tools and utilities
  adminer:
    image: adminer:latest
    container_name: corner-league-adminer
    restart: unless-stopped
    ports:
      - "8081:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=postgres
      - ADMINER_DESIGN=pepa-linha
    depends_on:
      - postgres
    networks:
      - corner-league-network

  # Redis Commander for Redis management
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: corner-league-redis-commander
    restart: unless-stopped
    ports:
      - "8082:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379
      - HTTP_USER=admin
      - HTTP_PASSWORD=admin
    depends_on:
      - redis
    networks:
      - corner-league-network

volumes:
  postgres_data:
  redis_data: