"""College Football Phase 3: Seed Data for Bowl Games, CFP, and Championships

Revision ID: college_football_phase3_seed
Revises: college_football_phase3
Create Date: 2025-09-21 20:35:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import uuid
from datetime import datetime

# revision identifiers, used by Alembic.
revision = 'college_football_phase3_seed'
down_revision = 'college_football_phase3'
branch_labels = None
depends_on = None

def upgrade():
    """Insert comprehensive seed data for College Football Phase 3"""

    # Get connection for bulk inserts
    connection = op.get_bind()

    # =============================================================================
    # Bowl Games Seed Data
    # =============================================================================

    bowl_games_data = [
        # College Football Playoff Bowls
        {
            'id': str(uuid.uuid4()),
            'name': 'Rose Bowl Game',
            'slug': 'rose-bowl',
            'sponsor_name': None,
            'full_name': 'Rose Bowl Game presented by Capital One',
            'bowl_tier': 'new_years_six',
            'is_cfp_bowl': True,
            'is_new_years_six': True,
            'city': 'Pasadena',
            'state': 'California',
            'venue_name': 'Rose Bowl Stadium',
            'venue_capacity': 88565,
            'typical_date': 'January 1',
            'kickoff_time': '5:00 PM ET',
            'selection_criteria': 'cfp_semifinal',
            'selection_order': 1,
            'min_wins_required': 6,
            'primary_conference_tie_ins': '["Big Ten", "Pac-12"]',
            'secondary_conference_tie_ins': '[]',
            'at_large_eligible': True,
            'group_of_five_access': False,
            'total_payout': 35000000.00,
            'payout_per_team': 17500000.00,
            'payout_year': 2024,
            'first_played': 1902,
            'total_games_played': 110,
            'primary_tv_network': 'ESPN',
            'broadcast_time_slot': 'New Year\'s Day Prime Time',
            'trophy_name': 'Rose Bowl Trophy',
            'is_tradition_bowl': True,
            'weather_type': 'Warm Weather',
            'is_active': True
        },
        {
            'id': str(uuid.uuid4()),
            'name': 'Sugar Bowl',
            'slug': 'sugar-bowl',
            'sponsor_name': 'Allstate',
            'full_name': 'Allstate Sugar Bowl',
            'bowl_tier': 'new_years_six',
            'is_cfp_bowl': True,
            'is_new_years_six': True,
            'city': 'New Orleans',
            'state': 'Louisiana',
            'venue_name': 'Caesars Superdome',
            'venue_capacity': 73208,
            'typical_date': 'January 1',
            'kickoff_time': '8:45 PM ET',
            'selection_criteria': 'cfp_semifinal',
            'selection_order': 2,
            'min_wins_required': 6,
            'primary_conference_tie_ins': '["SEC", "Big 12"]',
            'secondary_conference_tie_ins': '[]',
            'at_large_eligible': True,
            'group_of_five_access': False,
            'total_payout': 35000000.00,
            'payout_per_team': 17500000.00,
            'payout_year': 2024,
            'first_played': 1935,
            'total_games_played': 89,
            'primary_tv_network': 'ESPN',
            'broadcast_time_slot': 'New Year\'s Day Night',
            'trophy_name': 'Sugar Bowl Trophy',
            'is_tradition_bowl': True,
            'weather_type': 'Dome',
            'is_active': True
        },
        {
            'id': str(uuid.uuid4()),
            'name': 'Orange Bowl',
            'slug': 'orange-bowl',
            'sponsor_name': 'Capital One',
            'full_name': 'Capital One Orange Bowl',
            'bowl_tier': 'new_years_six',
            'is_cfp_bowl': True,
            'is_new_years_six': True,
            'city': 'Miami Gardens',
            'state': 'Florida',
            'venue_name': 'Hard Rock Stadium',
            'venue_capacity': 65326,
            'typical_date': 'December 30',
            'kickoff_time': '8:00 PM ET',
            'selection_criteria': 'cfp_quarterfinal',
            'selection_order': 3,
            'min_wins_required': 6,
            'primary_conference_tie_ins': '["ACC", "SEC"]',
            'secondary_conference_tie_ins': '[]',
            'at_large_eligible': True,
            'group_of_five_access': False,
            'total_payout': 35000000.00,
            'payout_per_team': 17500000.00,
            'payout_year': 2024,
            'first_played': 1935,
            'total_games_played': 89,
            'primary_tv_network': 'ESPN',
            'broadcast_time_slot': 'New Year\'s Eve Prime Time',
            'trophy_name': 'Orange Bowl Trophy',
            'is_tradition_bowl': True,
            'weather_type': 'Warm Weather',
            'is_active': True
        },
        {
            'id': str(uuid.uuid4()),
            'name': 'Cotton Bowl Classic',
            'slug': 'cotton-bowl',
            'sponsor_name': 'Goodyear',
            'full_name': 'Goodyear Cotton Bowl Classic',
            'bowl_tier': 'new_years_six',
            'is_cfp_bowl': True,
            'is_new_years_six': True,
            'city': 'Arlington',
            'state': 'Texas',
            'venue_name': 'AT&T Stadium',
            'venue_capacity': 80000,
            'typical_date': 'January 1',
            'kickoff_time': '1:00 PM ET',
            'selection_criteria': 'cfp_quarterfinal',
            'selection_order': 4,
            'min_wins_required': 6,
            'primary_conference_tie_ins': '["Big 12", "SEC"]',
            'secondary_conference_tie_ins': '[]',
            'at_large_eligible': True,
            'group_of_five_access': False,
            'total_payout': 35000000.00,
            'payout_per_team': 17500000.00,
            'payout_year': 2024,
            'first_played': 1937,
            'total_games_played': 87,
            'primary_tv_network': 'ESPN',
            'broadcast_time_slot': 'New Year\'s Day Afternoon',
            'trophy_name': 'Cotton Bowl Trophy',
            'is_tradition_bowl': True,
            'weather_type': 'Dome',
            'is_active': True
        },
        {
            'id': str(uuid.uuid4()),
            'name': 'Peach Bowl',
            'slug': 'peach-bowl',
            'sponsor_name': 'Chick-fil-A',
            'full_name': 'Chick-fil-A Peach Bowl',
            'bowl_tier': 'new_years_six',
            'is_cfp_bowl': True,
            'is_new_years_six': True,
            'city': 'Atlanta',
            'state': 'Georgia',
            'venue_name': 'Mercedes-Benz Stadium',
            'venue_capacity': 71000,
            'typical_date': 'December 31',
            'kickoff_time': '12:00 PM ET',
            'selection_criteria': 'cfp_quarterfinal',
            'selection_order': 5,
            'min_wins_required': 6,
            'primary_conference_tie_ins': '[]',
            'secondary_conference_tie_ins': '[]',
            'at_large_eligible': True,
            'group_of_five_access': False,
            'total_payout': 35000000.00,
            'payout_per_team': 17500000.00,
            'payout_year': 2024,
            'first_played': 1968,
            'total_games_played': 56,
            'primary_tv_network': 'ESPN',
            'broadcast_time_slot': 'New Year\'s Eve Noon',
            'trophy_name': 'Peach Bowl Trophy',
            'is_tradition_bowl': False,
            'weather_type': 'Dome',
            'is_active': True
        },
        {
            'id': str(uuid.uuid4()),
            'name': 'Fiesta Bowl',
            'slug': 'fiesta-bowl',
            'sponsor_name': 'PlayStation',
            'full_name': 'PlayStation Fiesta Bowl',
            'bowl_tier': 'new_years_six',
            'is_cfp_bowl': True,
            'is_new_years_six': True,
            'city': 'Glendale',
            'state': 'Arizona',
            'venue_name': 'State Farm Stadium',
            'venue_capacity': 63400,
            'typical_date': 'January 1',
            'kickoff_time': '1:00 PM ET',
            'selection_criteria': 'group_of_five_access',
            'selection_order': 6,
            'min_wins_required': 6,
            'primary_conference_tie_ins': '[]',
            'secondary_conference_tie_ins': '[]',
            'at_large_eligible': True,
            'group_of_five_access': True,
            'total_payout': 35000000.00,
            'payout_per_team': 17500000.00,
            'payout_year': 2024,
            'first_played': 1971,
            'total_games_played': 53,
            'primary_tv_network': 'ESPN',
            'broadcast_time_slot': 'New Year\'s Day Afternoon',
            'trophy_name': 'Fiesta Bowl Trophy',
            'is_tradition_bowl': False,
            'weather_type': 'Dome',
            'is_active': True
        },

        # Major Bowl Games
        {
            'id': str(uuid.uuid4()),
            'name': 'Citrus Bowl',
            'slug': 'citrus-bowl',
            'sponsor_name': 'Vrbo',
            'full_name': 'Vrbo Citrus Bowl',
            'bowl_tier': 'major',
            'is_cfp_bowl': False,
            'is_new_years_six': False,
            'city': 'Orlando',
            'state': 'Florida',
            'venue_name': 'Camping World Stadium',
            'venue_capacity': 65000,
            'typical_date': 'January 1',
            'kickoff_time': '1:00 PM ET',
            'selection_criteria': 'conference_tie_in',
            'selection_order': 1,
            'min_wins_required': 6,
            'primary_conference_tie_ins': '["SEC", "Big Ten"]',
            'secondary_conference_tie_ins': '[]',
            'at_large_eligible': False,
            'group_of_five_access': False,
            'total_payout': 8200000.00,
            'payout_per_team': 4100000.00,
            'payout_year': 2024,
            'first_played': 1947,
            'total_games_played': 77,
            'primary_tv_network': 'ABC',
            'broadcast_time_slot': 'New Year\'s Day Afternoon',
            'trophy_name': 'Citrus Bowl Trophy',
            'is_tradition_bowl': False,
            'weather_type': 'Warm Weather',
            'is_active': True
        },
        {
            'id': str(uuid.uuid4()),
            'name': 'Outback Bowl',
            'slug': 'outback-bowl',
            'sponsor_name': 'ReliaQuest',
            'full_name': 'ReliaQuest Bowl',
            'bowl_tier': 'major',
            'is_cfp_bowl': False,
            'is_new_years_six': False,
            'city': 'Tampa',
            'state': 'Florida',
            'venue_name': 'Raymond James Stadium',
            'venue_capacity': 65890,
            'typical_date': 'January 1',
            'kickoff_time': '12:00 PM ET',
            'selection_criteria': 'conference_tie_in',
            'selection_order': 2,
            'min_wins_required': 6,
            'primary_conference_tie_ins': '["SEC", "Big Ten"]',
            'secondary_conference_tie_ins': '[]',
            'at_large_eligible': False,
            'group_of_five_access': False,
            'total_payout': 6400000.00,
            'payout_per_team': 3200000.00,
            'payout_year': 2024,
            'first_played': 1986,
            'total_games_played': 38,
            'primary_tv_network': 'ESPN',
            'broadcast_time_slot': 'New Year\'s Day Noon',
            'trophy_name': 'ReliaQuest Bowl Trophy',
            'is_tradition_bowl': False,
            'weather_type': 'Warm Weather',
            'is_active': True
        },

        # Regional Bowl Games
        {
            'id': str(uuid.uuid4()),
            'name': 'Holiday Bowl',
            'slug': 'holiday-bowl',
            'sponsor_name': 'Tony the Tiger Sun',
            'full_name': 'Tony the Tiger Sun Bowl',
            'bowl_tier': 'regional',
            'is_cfp_bowl': False,
            'is_new_years_six': False,
            'city': 'San Diego',
            'state': 'California',
            'venue_name': 'Petco Park',
            'venue_capacity': 70000,
            'typical_date': 'December 27',
            'kickoff_time': '8:00 PM ET',
            'selection_criteria': 'conference_tie_in',
            'selection_order': 1,
            'min_wins_required': 6,
            'primary_conference_tie_ins': '["Pac-12", "ACC"]',
            'secondary_conference_tie_ins': '[]',
            'at_large_eligible': True,
            'group_of_five_access': False,
            'total_payout': 4300000.00,
            'payout_per_team': 2150000.00,
            'payout_year': 2024,
            'first_played': 1978,
            'total_games_played': 46,
            'primary_tv_network': 'Fox',
            'broadcast_time_slot': 'Holiday Week Prime Time',
            'trophy_name': 'Holiday Bowl Trophy',
            'is_tradition_bowl': False,
            'weather_type': 'Warm Weather',
            'is_active': True
        },
        {
            'id': str(uuid.uuid4()),
            'name': 'Alamo Bowl',
            'slug': 'alamo-bowl',
            'sponsor_name': 'Valero',
            'full_name': 'Valero Alamo Bowl',
            'bowl_tier': 'regional',
            'is_cfp_bowl': False,
            'is_new_years_six': False,
            'city': 'San Antonio',
            'state': 'Texas',
            'venue_name': 'Alamodome',
            'venue_capacity': 64000,
            'typical_date': 'December 29',
            'kickoff_time': '9:15 PM ET',
            'selection_criteria': 'conference_tie_in',
            'selection_order': 2,
            'min_wins_required': 6,
            'primary_conference_tie_ins': '["Big 12", "Pac-12"]',
            'secondary_conference_tie_ins': '[]',
            'at_large_eligible': True,
            'group_of_five_access': False,
            'total_payout': 4700000.00,
            'payout_per_team': 2350000.00,
            'payout_year': 2024,
            'first_played': 1993,
            'total_games_played': 31,
            'primary_tv_network': 'ESPN',
            'broadcast_time_slot': 'Holiday Week Prime Time',
            'trophy_name': 'Alamo Bowl Trophy',
            'is_tradition_bowl': False,
            'weather_type': 'Dome',
            'is_active': True
        },

        # Minor Bowl Games (representative sample)
        {
            'id': str(uuid.uuid4()),
            'name': 'Gasparilla Bowl',
            'slug': 'gasparilla-bowl',
            'sponsor_name': 'Bad Boy Mowers',
            'full_name': 'Bad Boy Mowers Gasparilla Bowl',
            'bowl_tier': 'minor',
            'is_cfp_bowl': False,
            'is_new_years_six': False,
            'city': 'Tampa',
            'state': 'Florida',
            'venue_name': 'Raymond James Stadium',
            'venue_capacity': 65890,
            'typical_date': 'December 23',
            'kickoff_time': '6:30 PM ET',
            'selection_criteria': 'open_selection',
            'selection_order': 1,
            'min_wins_required': 6,
            'primary_conference_tie_ins': '[]',
            'secondary_conference_tie_ins': '["American", "Conference USA"]',
            'at_large_eligible': True,
            'group_of_five_access': True,
            'total_payout': 1200000.00,
            'payout_per_team': 600000.00,
            'payout_year': 2024,
            'first_played': 2008,
            'total_games_played': 16,
            'primary_tv_network': 'ESPN',
            'broadcast_time_slot': 'Pre-Christmas',
            'trophy_name': 'Gasparilla Bowl Trophy',
            'is_tradition_bowl': False,
            'weather_type': 'Warm Weather',
            'is_active': True
        },
        {
            'id': str(uuid.uuid4()),
            'name': 'Famous Idaho Potato Bowl',
            'slug': 'famous-idaho-potato-bowl',
            'sponsor_name': 'Famous Idaho Potato',
            'full_name': 'Famous Idaho Potato Bowl',
            'bowl_tier': 'minor',
            'is_cfp_bowl': False,
            'is_new_years_six': False,
            'city': 'Boise',
            'state': 'Idaho',
            'venue_name': 'Albertsons Stadium',
            'venue_capacity': 36387,
            'typical_date': 'December 22',
            'kickoff_time': '3:30 PM ET',
            'selection_criteria': 'regional_tie_in',
            'selection_order': 1,
            'min_wins_required': 6,
            'primary_conference_tie_ins': '[]',
            'secondary_conference_tie_ins': '["Mountain West", "MAC"]',
            'at_large_eligible': True,
            'group_of_five_access': True,
            'total_payout': 750000.00,
            'payout_per_team': 375000.00,
            'payout_year': 2024,
            'first_played': 1997,
            'total_games_played': 27,
            'primary_tv_network': 'ESPN',
            'broadcast_time_slot': 'Pre-Christmas Afternoon',
            'trophy_name': 'Famous Idaho Potato Bowl Trophy',
            'is_tradition_bowl': False,
            'weather_type': 'Cold Weather',
            'is_active': True
        }
    ]

    # Insert bowl games
    for bowl_data in bowl_games_data:
        bowl_data['created_at'] = datetime.utcnow()
        bowl_data['updated_at'] = datetime.utcnow()

    # Insert bowl games in batches
    op.bulk_insert(
        sa.table('bowl_games',
            sa.column('id', postgresql.UUID),
            sa.column('name', sa.String),
            sa.column('slug', sa.String),
            sa.column('sponsor_name', sa.String),
            sa.column('full_name', sa.String),
            sa.column('bowl_tier', sa.String),
            sa.column('is_cfp_bowl', sa.Boolean),
            sa.column('is_new_years_six', sa.Boolean),
            sa.column('city', sa.String),
            sa.column('state', sa.String),
            sa.column('venue_name', sa.String),
            sa.column('venue_capacity', sa.Integer),
            sa.column('typical_date', sa.String),
            sa.column('kickoff_time', sa.String),
            sa.column('selection_criteria', sa.String),
            sa.column('selection_order', sa.Integer),
            sa.column('min_wins_required', sa.Integer),
            sa.column('primary_conference_tie_ins', sa.String),
            sa.column('secondary_conference_tie_ins', sa.String),
            sa.column('at_large_eligible', sa.Boolean),
            sa.column('group_of_five_access', sa.Boolean),
            sa.column('total_payout', sa.Numeric),
            sa.column('payout_per_team', sa.Numeric),
            sa.column('payout_year', sa.Integer),
            sa.column('first_played', sa.Integer),
            sa.column('total_games_played', sa.Integer),
            sa.column('primary_tv_network', sa.String),
            sa.column('broadcast_time_slot', sa.String),
            sa.column('trophy_name', sa.String),
            sa.column('is_tradition_bowl', sa.Boolean),
            sa.column('weather_type', sa.String),
            sa.column('is_active', sa.Boolean),
            sa.column('created_at', sa.DateTime),
            sa.column('updated_at', sa.DateTime)
        ),
        bowl_games_data
    )

    # =============================================================================
    # Major Rivalry Games Seed Data
    # =============================================================================

    rivalry_games_data = [
        {
            'id': str(uuid.uuid4()),
            'name': 'The Game',
            'slug': 'michigan-ohio-state',
            'nickname': 'The Game',
            'rivalry_type': 'conference',
            'intensity_level': 10,
            'has_trophy': False,
            'trophy_name': None,
            'trophy_description': None,
            'first_meeting': 1897,
            'total_meetings': 119,
            'team1_wins': 51,  # Michigan
            'team2_wins': 60,  # Ohio State
            'ties': 6,
            'current_streak': 3,  # Ohio State
            'longest_streak': 9,  # Michigan 1901-1909
            'is_annual': True,
            'typical_date': 'Last Saturday in November',
            'alternates_venue': True,
            'neutral_site_games': False,
            'conference_implications': True,
            'playoff_implications': True,
            'recruiting_impact': 'National',
            'tv_tradition': 'ABC/ESPN Noon Kickoff',
            'cultural_significance': 'One of the greatest rivalries in college football history',
            'is_active': True,
            'last_played_year': 2023
        },
        {
            'id': str(uuid.uuid4()),
            'name': 'Iron Bowl',
            'slug': 'alabama-auburn',
            'nickname': 'Iron Bowl',
            'rivalry_type': 'regional',
            'intensity_level': 10,
            'has_trophy': False,
            'trophy_name': None,
            'trophy_description': None,
            'first_meeting': 1893,
            'total_meetings': 87,
            'team1_wins': 49,  # Alabama
            'team2_wins': 37,  # Auburn
            'ties': 1,
            'current_streak': 4,  # Alabama
            'longest_streak': 9,  # Alabama 1973-1981
            'is_annual': True,
            'typical_date': 'Fourth Saturday in November',
            'alternates_venue': True,
            'neutral_site_games': False,
            'conference_implications': True,
            'playoff_implications': True,
            'recruiting_impact': 'Regional',
            'tv_tradition': 'CBS 3:30 PM Kickoff',
            'cultural_significance': 'Divides the state of Alabama down the middle',
            'is_active': True,
            'last_played_year': 2023
        },
        {
            'id': str(uuid.uuid4()),
            'name': 'Red River Showdown',
            'slug': 'texas-oklahoma',
            'nickname': 'Red River Showdown',
            'rivalry_type': 'conference',
            'intensity_level': 9,
            'has_trophy': True,
            'trophy_name': 'Golden Hat',
            'trophy_description': 'Golden hat trophy awarded to the winner',
            'first_meeting': 1900,
            'total_meetings': 119,
            'team1_wins': 63,  # Texas
            'team2_wins': 50,  # Oklahoma
            'ties': 5,
            'current_streak': 2,  # Texas
            'longest_streak': 8,  # Oklahoma 2000-2007
            'is_annual': True,
            'typical_date': 'Second Saturday in October',
            'alternates_venue': False,
            'neutral_site_games': True,
            'conference_implications': True,
            'playoff_implications': True,
            'recruiting_impact': 'Regional',
            'tv_tradition': 'ABC/Fox at Cotton Bowl during State Fair of Texas',
            'cultural_significance': 'Played at neutral site during State Fair of Texas',
            'is_active': True,
            'last_played_year': 2023
        },
        {
            'id': str(uuid.uuid4()),
            'name': 'Army-Navy Game',
            'slug': 'army-navy',
            'nickname': 'America\'s Game',
            'rivalry_type': 'national',
            'intensity_level': 10,
            'has_trophy': True,
            'trophy_name': 'Commander-in-Chief\'s Trophy',
            'trophy_description': 'Awarded to winner of triangular series with Air Force',
            'first_meeting': 1890,
            'total_meetings': 123,
            'team1_wins': 53,  # Army
            'team2_wins': 62,  # Navy
            'ties': 7,
            'current_streak': 1,  # Navy
            'longest_streak': 14,  # Navy 2002-2015
            'is_annual': True,
            'typical_date': 'Second Saturday in December',
            'alternates_venue': False,
            'neutral_site_games': True,
            'conference_implications': False,
            'playoff_implications': False,
            'recruiting_impact': 'National',
            'tv_tradition': 'CBS National Broadcast',
            'cultural_significance': 'America\'s Game - honors military service academies',
            'is_active': True,
            'last_played_year': 2023
        },
        {
            'id': str(uuid.uuid4()),
            'name': 'Bedlam Series',
            'slug': 'oklahoma-oklahoma-state',
            'nickname': 'Bedlam',
            'rivalry_type': 'regional',
            'intensity_level': 8,
            'has_trophy': False,
            'trophy_name': None,
            'trophy_description': None,
            'first_meeting': 1904,
            'total_meetings': 116,
            'team1_wins': 90,  # Oklahoma
            'team2_wins': 18,  # Oklahoma State
            'ties': 7,
            'current_streak': 2,  # Oklahoma
            'longest_streak': 19,  # Oklahoma 1946-1964
            'is_annual': True,
            'typical_date': 'Late November',
            'alternates_venue': True,
            'neutral_site_games': False,
            'conference_implications': True,
            'playoff_implications': True,
            'recruiting_impact': 'Regional',
            'tv_tradition': 'ESPN/Fox Regional Coverage',
            'cultural_significance': 'In-state rivalry known as Bedlam',
            'is_active': True,
            'last_played_year': 2023
        }
    ]

    # Insert rivalry games
    for rivalry_data in rivalry_games_data:
        rivalry_data['created_at'] = datetime.utcnow()
        rivalry_data['updated_at'] = datetime.utcnow()

    op.bulk_insert(
        sa.table('rivalry_games',
            sa.column('id', postgresql.UUID),
            sa.column('name', sa.String),
            sa.column('slug', sa.String),
            sa.column('nickname', sa.String),
            sa.column('rivalry_type', sa.String),
            sa.column('intensity_level', sa.Integer),
            sa.column('has_trophy', sa.Boolean),
            sa.column('trophy_name', sa.String),
            sa.column('trophy_description', sa.Text),
            sa.column('first_meeting', sa.Integer),
            sa.column('total_meetings', sa.Integer),
            sa.column('team1_wins', sa.Integer),
            sa.column('team2_wins', sa.Integer),
            sa.column('ties', sa.Integer),
            sa.column('current_streak', sa.Integer),
            sa.column('longest_streak', sa.Integer),
            sa.column('is_annual', sa.Boolean),
            sa.column('typical_date', sa.String),
            sa.column('alternates_venue', sa.Boolean),
            sa.column('neutral_site_games', sa.Boolean),
            sa.column('conference_implications', sa.Boolean),
            sa.column('playoff_implications', sa.Boolean),
            sa.column('recruiting_impact', sa.String),
            sa.column('tv_tradition', sa.String),
            sa.column('cultural_significance', sa.Text),
            sa.column('is_active', sa.Boolean),
            sa.column('last_played_year', sa.Integer),
            sa.column('created_at', sa.DateTime),
            sa.column('updated_at', sa.DateTime)
        ),
        rivalry_games_data
    )

    print(f"Successfully inserted {len(bowl_games_data)} bowl games and {len(rivalry_games_data)} rivalry games")


def downgrade():
    """Remove College Football Phase 3 seed data"""

    # Delete rivalry games
    op.execute("DELETE FROM rivalry_games")

    # Delete bowl games
    op.execute("DELETE FROM bowl_games")

    print("Successfully removed College Football Phase 3 seed data")